### ISSUE TITLE
Add support to input source object (not only strings)

### ISSUE THREAD

**Issue by ajeiie120120** [developit/rollup-plugin-preserve-shebang#10]
Hi,

let's say I have this project structure

```
src
|-- cli
|    |-- script1.js
|    |-- script2.js
|
|-- index.js
package.json
```
and I want to create a separate chunk for each source file, so i pass this object to the **rollup** configuration `input`:

`
{ 
	'cli/script1': '/src/cli/script1.js',
	'cli/script2': '/src/cli/script2.js',
	index: '/src/index.js' 
}
`

the plugin will go in exception with this message:

`
[!] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type object
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type object
    at Object.openSync (fs.js:430:3)
    at Object.readFileSync (fs.js:343:35)
    at processEntry (H:\vs_workspace\wws-ui-toolbox\node_modules\rollup-plugin-preserve-shebang\dist\index.js:25:32)
    at Object.options (H:\vs_workspace\wws-ui-toolbox\node_modules\rollup-plugin-preserve-shebang\dist\index.js:37:5)
    at applyOptionHook (H:\vs_workspace\wws-ui-toolbox\node_modules\rollup\dist\rollup.js:17106:31)
    at Array.reduce (<anonymous>)
    at getInputOptions (H:\vs_workspace\wws-ui-toolbox\node_modules\rollup\dist\rollup.js:17127:54)
    at Object.<anonymous> (H:\vs_workspace\wws-ui-toolbox\node_modules\rollup\dist\rollup.js:17200:30)
    at Generator.next (<anonymous>)
    at H:\vs_workspace\wws-ui-toolbox\node_modules\rollup\dist\rollup.js:52:71
`

probably due to this line of code

**dist/index.js**
`
(line 23) var contents = _fs2.default.readFileSync(entry, 'utf8');
`

Can support to object input source be added?

Thanks.

**Comment by developit** [comment]
This is fixed in [1.0.0](https://github.com/developit/rollup-plugin-preserve-shebang/releases/tag/1.0.0) - the plugin is now a proper Rollup plugin and doesn't read from the filesystem directly.
